export const AUTOMATION_DLQ_DEFAULT_TOPIC = 'automation.events.dlq'

const AUTOMATION_KF_TOPIC = process.env.AUTOMATION_KF_TOPIC
const AUTOMATION_DLQ_TOPIC = process.env.AUTOMATION_DLQ_TOPIC

export enum EventType {
  AUTOMATION_EVENT = 'AUTOMATION_EVENT',
  AUTOMATION_DLQ_EVENT = 'AUTOMATION_DLQ_EVENT',
}

export const eventTypeTopicMap = {
  [EventType.AUTOMATION_EVENT.toString()]: AUTOMATION_KF_TOPIC,
  [EventType.AUTOMATION_DLQ_EVENT.toString()]:
    AUTOMATION_DLQ_TOPIC || AUTOMATION_DLQ_DEFAULT_TOPIC,
}
